### ISSUE TITLE
bpf(BPF_PROG_LOAD) -EINVAL

### ISSUE THREAD

**Issue by pavlinux** [oracle-samples/bpftune#13]
.....

**Comment by pavlinux** [comment]
pftune -sD 
root@amd64:/media/kernel/bpftune/src# bpftune: bpftune works fully
bpftune: bpftune supports per-netns policy (via netns cookie)
bpftune: could not load skeleton: Invalid argument
bpftune: error initializing '/usr/lib64/bpftune//route_table_tuner.so: Invalid argument
bpftune: could not open /proc/sys/net/ipv6/neigh/default/gc_interval (netns fd 0) for reading: No such file or directory
bpftune: error reading tunable 'net.ipv6.neigh.default.gc_interval': No such file or directory
bpftune: error initializing '/usr/lib64/bpftune//neigh_table_tuner.so: No such file or directory
bpftune: could not load skeleton: Invalid argument
bpftune: error initializing '/usr/lib64/bpftune//tcp_cong_tuner.so: Invalid argument
bpftune: could not load skeleton: Invalid argument
bpftune: error initializing '/usr/lib64/bpftune//route_table_tuner.so: Invalid argument
bpftune: could not open /proc/sys/net/ipv6/neigh/default/gc_interval (netns fd 0) for reading: No such file or directory
bpftune: error reading tunable 'net.ipv6.neigh.default.gc_interval': No such file or directory
bpftune: error initializing '/usr/lib64/bpftune//neigh_table_tuner.so: No such file or directory
bpftune: could not load skeleton: Invalid argument
bpftune: error initializing '/usr/lib64/bpftune//tcp_cong_tuner.so: Invalid argument

**Comment by alan-maguire** [comment]
thanks for the report. What distro is this (I see it's a 5.10 kernel from above)? Is kernel/module BTF available in /sys/kernel/btf ?

**Comment by pavlinux** [comment]
> 

* Debian 10.13
* Kernel custom (config in attach)
* clang version 17.0.0 (https://github.com/llvm/llvm-project.git c9eec3b085de0f7ce885cbdf9d35d9159ddd272a)
* pahole (latest kernel.org)
* libbpf (latest gisthub)
* bpftool  (latest gisthub)
* 
[config.gz](https://github.com/oracle-samples/bpftune/files/11958748/config.gz)

**Comment by alan-maguire** [comment]
do the above failures go away with ipv6 disabled as per other issue? if so, let's use this one to track better bpftune handling of the ipv6 disabled case..

**Comment by pavlinux** [comment]
> do the above failures go away with ipv6 disabled as per other issue? if so, let's use this one to track better bpftune handling of the ipv6 disabled case..
* Enabled IPv6 in the kernel
* compiled as a module
* net.ipv6.conf.default.disable_ipv6 = 0
```
# bpftune -s

bpftune: bpftune works fully
bpftune: bpftune supports per-netns policy (via netns cookie)
bpftune: could not load skeleton: Invalid argument
bpftune: error initializing '/usr/lib64/bpftune//tcp_cong_tuner.so: Invalid argument
bpftune: could not load skeleton: No such process
bpftune: error initializing '/usr/lib64/bpftune//route_table_tuner.so: No such process
bpftune: could not load skeleton: Invalid argument
bpftune: error initializing '/usr/local/lib64/bpftune//tcp_cong_tuner.so: Invalid argument
bpftune: could not load skeleton: No such process
bpftune: error initializing '/usr/local/lib64/bpftune//route_table_tuner.so: No such process
```

**Comment by pavlinux** [comment]
```
# bpftune -ds
bpftune: libbpf: prog 'entry__fib6_age': failed to find kernel BTF type ID of 'fib6_age': -3
bpftune: libbpf: prog 'entry__fib6_age': failed to prepare load attributes: -3
bpftune: libbpf: prog 'entry__fib6_age': failed to load: -3
bpftune: libbpf: failed to load object 'route_table_tuner_bpf'
bpftune: libbpf: failed to load BPF skeleton 'route_table_tuner_bpf': -3
bpftune: could not load skeleton: No such process
bpftune: drop caps (count 0)
bpftune: error initializing '/usr/local/lib64/bpftune//route_table_tuner.so: No such process
```

**Comment by pavlinux** [comment]
Write the requirements for the kernel config. Or handle all exceptions.

**Comment by pavlinux** [comment]
```
bpftune: searching /usr/lib64/bpftune/ for plugins...
bpftune: found lib /usr/lib64/bpftune//tcp_cong_tuner.so, init
bpftune: set caps (count 1)
bpftune: drop caps (count 0)
bpftune: calling init for '/usr/lib64/bpftune//tcp_cong_tuner.so
bpftune: set caps (count 1)
bpftune: could not init module '/lib/modules/5.10.186/kernel/net/ipv4/tcp_bbr.ko'
bpftune: drop caps (count 0)
bpftune: set caps (count 1)
```

```
# ls -la /lib/modules/5.10.186/kernel/net/ipv4/tcp_bbr.ko
-rw-r--r-- 1 root root 791440 Jul  7 19:38 /lib/modules/5.10.186/kernel/net/ipv4/tcp_bbr.ko
```

**Comment by pavlinux** [comment]
```
71: (07) r4 += -40
; if (bpf_getsockopt(ctx, SOL_TCP, TCP_CONGESTION, &buf, sizeof(buf)) ||
72: (bf) r1 = r6
73: (b7) r2 = 6
74: (b7) r3 = 13
75: (b7) r5 = 16
76: (85) call bpf_getsockopt#57
unknown func bpf_getsockopt#57
processed 68 insns (limit 1000000) max_states_per_insn 0 total_states 6 peak_states 6 mark_read 4
-- END PROG LOAD LOG --
bpftune: libbpf: prog 'bpftune_cong_iter': failed to load: -22
bpftune: libbpf: failed to load object 'tcp_cong_tuner_bpf'
bpftune: libbpf: failed to load BPF skeleton 'tcp_cong_tuner_bpf': -22
bpftune: could not load skeleton: Invalid argument
bpftune: drop caps (count 0)
bpftune: error initializing '/usr/lib64/bpftune//tcp_cong_tuner.so: Invalid argument
```

Where is live **bpf_getsockopt( )** ???  In kernel only **_bpf_getsockopt** https://elixir.bootlin.com/linux/v6.1.38/source/net/core/filter.c#L5334

**Comment by alan-maguire** [comment]
bpf_getsockopt() is a BPF helper that's existed in the kernel since around the 4.19 kernel. i checked and bpf tcp iterator support was added prior to 5.10, but support for bpf_getsockopt was not added until 5.14 via commit 3cee6fb8e69e. i will adjust the support test to include this so bpftune falls back to legacy mode.

**Comment by alan-maguire** [comment]
above is done via https://github.com/oracle-samples/bpftune/pull/25
